Fixed navbar dropdown position and hover effects
TUB-DVG/wissen-digital-ewb pull request #168
Opened 2024-10-28 10:10 UTC by nlongn22

closes #167

2024-10-30 19:43 UTC, expeditionengineer requested changes

2024-10-30 19:43 UTC, expeditionengineer commented on webcentral/src/templates/partials/_navbar.html
> +.nav-link:hover {
can you please add the stylesheets to the scss-files and remove them here

2024-11-12 13:08 UTC, c0nb4 commented
As dicussed this will be merged. Reopen issue for mobile optimization.

2024-11-13 07:15 UTC, expeditionengineer approved these changes

2024-11-13 07:15 UTC, expeditionengineer commented
perfect, the navbar is now working

2024-11-13 07:16 UTC, merged